site_name: Bhargavi's Portfolio
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: images/MyPhoto.jpg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom

  
plugins:
  - search
  - tags
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

nav:
    - Home: index.md
    - Projects: 
       - Projects Overview: Projects/projects.md
       - About Me: Projects/about.md
       - Childhood: Projects/Childhood.md
    - Tags: tags.md
    - Blog:
       - blog/index.md

extra_css:
  - styles/overrides.css
  - extra_colors.css
