name: Final-Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      - name: Build
        run: mkdocs build --strict

      - name: Upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

      - name: Deploy
        uses: actions/deploy-pages@v3
