name: Nuclear-Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install mkdocs
          mkdocs build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./site
      - uses: actions/deploy-pages@v3
